import { configureStore } from "@reduxjs/toolkit";
import CounterSlice from "./slices/CounterSlice";


//to create global store in which centeralized data is present , use configureStore method
const Store = configureStore( {
 //   The reducer parameter is a function that takes the current state and an action object, and returns the new state of the application after applying the changes described in 
//    the action. This function is responsible for updating the state of your application in response to actions dispatched by your components or other parts of your application.
//The reducer key is an object with a single key-value pair, where the key is "counter", 
//and the value is the reducer function of the CounterSlice object that was generated by createSlice.
 
reducer:{
        //slice name is key and  value is   reducer inside the counter slice function 
        counter: CounterSlice.reducer
    },
}) 

export default Store;